############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Oria"
url = "/oria"
weight = 3

[[main]]
name = "Platform"
url = "/platform"
weight = 4

[[main]]
name = "Impact"
url = "/impact"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6

[[main]]
name = "Donate"
url = "/donate"
weight = 7

[[main]]
name = "Invest"
url = "/invest"
weight = 8


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
